# This is a basic workflow to help you get started with Actions
name: Lint

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: mypy
        run: mypy ./
      - name: flake8
        run: flake8 ./
